### ISSUE TITLE
re: large scale ghidra analysis

### ISSUE THREAD

**Issue by dev747368** [0x6d696368/ghidra_scripts#1]
@0x6d696368 - I might be able to help you out.  You could start a ticket and we could talk there.  Or here.

**Comment by 0x6d696368** [comment]
Hi!

I wrote some bash that collects the CentOS static libraries and uses Ghidra headless to generate Function ID datasets with them. It's using `CreateMultipleLibraries.java`, `FunctionIDHeadlessPrescript.java` and `FunctionIDHeadlessPostscript.java`. I should be able to spread the processing via Ghidra server in the future.

- Blog post: https://blog.threatrack.de/2019/09/20/ghidra-fid-generator/
- Github (with code): https://github.com/threatrack/ghidra-fid-generator

If you got any comments for improvements I'd be happy to hear them!

Regarding organizing the .fidb. What's a good granularity?
- `library-version-release.fidb` (e.g. openssl-static-1.0.2k-19.el7.x86_64.fidb)
- `library-version.fidb` (including multiple minor releases of the lib)
- `library-.fidb` (including all versions of the lib)
- `el7.x86_64.fidb` (including all libs of el7 x86_64)

Regarding the cleanup: It seems `RemoveFunctions.java` is rather Visual Studio library specific. But using the hashes in there won't hurt, right? But it should be extended with cleanup for newly ingested libraries.

**Comment by dev747368** [comment]
So, I'm going to have to disappoint you a bit, in that I'm mostly familiar with the ingest side of things.  In your tweet, it seemed like you were hitting some obstacles with that as well.

When I was working on importing the MS VS libs, I worked on a couple of scripts that are in the distro... MSLibBatchImportGenerator and MSLibBatchImportWorker.  Obviously they don't apply directly to your effort, but some of the ideas might help you.

As you've already run into, sometimes you need to blow away your stuff and re-do it, or, sometimes a headless analyzer session will hit something nasty and die.  Thats why I put some effort into the work-queue layout - so the batch could be re-run after fixing whatever problem, or a single bad input file won't clog other workers after its caused a failure.  I also split the import and analyze steps.

On our moderately sized server I could easily run 10+ concurrent workers importing/analyzing on the same Ghidra server project.  I think I was only limited by my user account's file handles quota.

**Comment by 0x6d696368** [comment]
> So, I'm going to have to disappoint you a bit, in that I'm mostly familiar with the ingest side of things. In your tweet, it seemed like you were hitting some obstacles with that as well.

No worries! I just like to hear other's mistakes so I can avoid them.

> When I was working on importing the MS VS libs, I worked on a couple of scripts that are in the distro... MSLibBatchImportGenerator and MSLibBatchImportWorker. Obviously they don't apply directly to your effort, but some of the ideas might help you.

Ah, that's nice. I can probably use them for other Windows libraries. And maybe for crowdsourcing FID creation in collaboration with the guys running ghidra-server.org

I will definitively reach out to you via the Ghidra issue tracker in case I'm having problems with the MSLib scripts or general data ingestion.

Thanks again for the great work on Ghidra!
